# Generated by Django 4.1 on 2024-01-04 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta_frecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=100, verbose_name='Pregunta')),
                ('respuesta', models.CharField(max_length=3000, verbose_name='Respuesta')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=100, verbose_name='Asunto')),
                ('reporte', models.CharField(max_length=3000, verbose_name='Reporte')),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('En proceso', 'En proceso'), ('Mantenimiento', 'Mantenimiento'), ('Resuelto', 'Resuelto')], default='Abierto', max_length=15, verbose_name='Estado')),
                ('solucion', models.CharField(blank=True, max_length=3000, verbose_name='Solución')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('agente_soporte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SoporteReporte', to=settings.AUTH_USER_MODEL, verbose_name='Agente de soporte')),
                ('gerente_soporte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GerenteReporte', to=settings.AUTH_USER_MODEL, verbose_name='Gerente de soporte')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reporte', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
