# Generated by Django 3.2 on 2021-04-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntas_frecuentes',
            name='respuesta',
            field=models.CharField(max_length=3000, verbose_name='Respuesta'),
        ),
    ]
