# Generated by Django 3.2 on 2021-05-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0005_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='atendido',
            field=models.BooleanField(default=False, verbose_name='Atendido'),
        ),
    ]
