# Generated by Django 3.2 on 2021-05-21 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0007_auto_20210520_1933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reporte',
        ),
    ]
