# Generated by Django 3.2 on 2021-05-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0011_auto_20210528_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='estado',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('En proceso', 'En proceso'), ('Mantenimiento', 'Mantenimiento'), ('Resuelto', 'Resuelto')], default='Abierto', max_length=15, verbose_name='Estado'),
        ),
    ]
