# Generated by Django 4.1 on 2023-08-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_gerente_soporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_nameMa',
        ),
    ]
