# Generated by Django 4.1 on 2024-02-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='state',
        ),
        migrations.RemoveField(
            model_name='postalcode',
            name='location',
        ),
        migrations.RemoveField(
            model_name='postalcode',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='croquis_de_del_predio',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='croquis_de_ubicacion',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='foto_de_posedor_actual',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='foto_del_predio',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='ortofoto',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='ubicacion_en_municipio',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='current_possessor_photo',
            field=models.ImageField(blank=True, null=True, upload_to='sales/current_possessor_photo'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='geographic_location',
            field=models.ImageField(blank=True, null=True, upload_to='sales/geographic_location'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='lat',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='long',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='main_map',
            field=models.ImageField(blank=True, null=True, upload_to='sales/main_map'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='property_photo',
            field=models.ImageField(blank=True, null=True, upload_to='sales/property_photo'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='satellite_location',
            field=models.ImageField(blank=True, null=True, upload_to='sales/satellite_location'),
        ),
        migrations.DeleteModel(
            name='Colindancias',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Municipality',
        ),
        migrations.DeleteModel(
            name='PostalCode',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
