# Generated by Django 4.1 on 2024-02-04 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0003_delete_perimeter'),
        ('ventas', '0002_remove_municipality_state_remove_postalcode_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='postal_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inmuebles', to='sig.postalcode'),
        ),
    ]
