# Generated by Django 4.1 on 2024-02-04 08:20

from django.db import migrations, models
import django.db.models.deletion

def corregir_postal_code(apps, schema_editor):
    Inmueble = apps.get_model('ventas', 'Inmueble')
    for inmueble in Inmueble.objects.all():
        if inmueble.postal_code == "":
            inmueble.postal_code = None  # Establece un valor que sea compatible con bigint o un valor por defecto válido.
            inmueble.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0003_delete_perimeter'),
        ('ventas', '0002_remove_municipality_state_remove_postalcode_location_and_more'),
    ]

    operations = [
        migrations.RunPython(corregir_postal_code),
        migrations.AlterField(
            model_name='inmueble',
            name='postal_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inmuebles', to='sig.postalcode'),
        ),
    ]
