# Generated by Django 4.1 on 2024-03-11 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_inmueble_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='user',
        ),
    ]
