# Generated by Django 3.2 on 2021-04-25 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0012_alter_inmueble_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='interesados',
            field=models.ManyToManyField(blank=True, default=None, related_name='me_interesan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to=settings.AUTH_USER_MODEL),
        ),
    ]
