# Generated by Django 3.2 on 2021-05-14 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_auto_20210425_0328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='creted',
            new_name='created',
        ),
    ]
