# Generated by Django 3.2 on 2021-05-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_alter_inmueble_interesados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='regimen_propiedad',
            field=models.CharField(choices=[('Privada', 'Privada'), ('Ejidal', 'Ejidal'), ('Comunal', 'Comunal')], default='Privada', max_length=15),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='status',
            field=models.CharField(choices=[('Oferta', 'Oferta'), ('Solicitud', 'Solicitud'), ('Vendido', 'Vendido')], default='Solicitud', max_length=10),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='uso_suelo',
            field=models.CharField(choices=[('Residencial', 'Residencial'), ('Actividades Productivas', 'Actividades Productivas'), ('Equipamiento', 'Equipamiento'), ('Infraestructura', 'Infraestructura'), ('Area Verde', 'Area Verde'), ('Otro', 'Otro')], default='Area Verde', max_length=25),
        ),
    ]
