# Generated by Django 4.1 on 2023-08-03 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0016_auto_20210519_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colindancias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Actual', 'Actual'), ('Anterior', 'Anterior')], max_length=15, null=True)),
                ('sur', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='inmueble',
            name='number_of',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='paraje',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='sig_location',
            field=models.CharField(blank=True, choices=[('Tepexoyuca', 'Tepexoyuca')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='status',
            field=models.CharField(choices=[('Oferta', 'Oferta'), ('Solicitud', 'Solicitud'), ('Vendido', 'Vendido'), ('Sig', 'Sig')], default='Solicitud', max_length=10),
        ),
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postal_codes_auth', to='ventas.location')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.municipality')),
            ],
        ),
        migrations.AddField(
            model_name='municipality',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.state'),
        ),
    ]
