# Generated by Django 4.1 on 2023-08-03 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0017_colindancias_location_municipality_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='colindancias',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to='ventas.colindancias'),
            preserve_default=False,
        ),
    ]
