# Generated by Django 4.1 on 2023-08-11 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0018_inmueble_colindancias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='colindancias',
        ),
        migrations.AddField(
            model_name='colindancias',
            name='este',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='colindancias',
            name='inmueble',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inmueble', to='ventas.inmueble'),
        ),
        migrations.AddField(
            model_name='colindancias',
            name='norte',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='colindancias',
            name='oeste',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='colindancias',
            name='status',
            field=models.CharField(blank=True, choices=[('Prop', 'Datos propietario'), ('TV', 'Datos terravision')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='colindancias',
            name='sur',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
    ]
