# Generated by Django 4.1 on 2023-08-06 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0018_inmueble_colindancias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='colindancias',
        ),
        migrations.AddField(
            model_name='colindancias',
            name='inmueble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inmueble', to='ventas.inmueble'),
        ),
        migrations.AlterField(
            model_name='colindancias',
            name='status',
            field=models.CharField(blank=True, choices=[('Prop', 'Datos propietario'), ('TV', 'Datos terravision')], max_length=45, null=True),
        ),
    ]
