# Generated by Django 4.1 on 2023-08-11 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0003_remove_propertysig_city_block_and_more'),
        ('ventas', '0019_remove_inmueble_colindancias_colindancias_este_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='perimetro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sig.perimeter'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sig.position'),
        ),
    ]
