# Generated by Django 4.1 on 2023-08-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0020_inmueble_perimetro_inmueble_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='perimetro',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='position',
        ),
    ]
