# Generated by Django 4.1 on 2023-08-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0021_remove_inmueble_perimetro_remove_inmueble_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='croquis_de_del_predio',
            field=models.ImageField(blank=True, null=True, upload_to='ventas/croquis_de_del_predio'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='croquis_de_ubicacion',
            field=models.ImageField(blank=True, null=True, upload_to='ventas/croquis_de_ubicacion'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='foto_de_posedor_actual',
            field=models.ImageField(blank=True, null=True, upload_to='ventas/foto_de_posesor_actual'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='foto_del_predio',
            field=models.ImageField(blank=True, null=True, upload_to='ventas/foto_del_predio'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='ortofoto',
            field=models.ImageField(blank=True, null=True, upload_to='ventas/photos_terrenos'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='ubicacion_en_municipio',
            field=models.ImageField(blank=True, null=True, upload_to='ventas/ubicacion_en_municipio'),
        ),
    ]
