# Generated by Django 4.1 on 2023-08-11 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0022_inmueble_croquis_de_del_predio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colindancias',
            name='inmueble',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colindacia', to='ventas.inmueble'),
        ),
    ]
