# Generated by Django 4.1 on 2023-08-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0002_cityblock_perimeter_position_propertysig_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertysig',
            name='city_block',
        ),
        migrations.RemoveField(
            model_name='propertysig',
            name='perimeter',
        ),
        migrations.RemoveField(
            model_name='propertysig',
            name='position',
        ),
        migrations.RemoveField(
            model_name='propertysig',
            name='profile',
        ),
        migrations.DeleteModel(
            name='CityBlock',
        ),
        migrations.DeleteModel(
            name='PropertySig',
        ),
    ]
