# Generated by Django 4.1 on 2024-02-04 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0003_delete_perimeter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionframe',
            name='rumbo',
        ),
    ]
