# Generated by Django 4.1 on 2024-02-27 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_inmueble_postal_code'),
        ('sig', '0005_constructionframe_rumbo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionframe',
            name='distancia',
        ),
        migrations.RemoveField(
            model_name='constructionframe',
            name='est',
        ),
        migrations.RemoveField(
            model_name='constructionframe',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='constructionframe',
            name='long',
        ),
        migrations.RemoveField(
            model_name='constructionframe',
            name='pv',
        ),
        migrations.RemoveField(
            model_name='constructionframe',
            name='rumbo',
        ),
        migrations.RemoveField(
            model_name='constructionframe',
            name='v',
        ),
        migrations.AlterField(
            model_name='constructionframe',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_frame', to='ventas.inmueble'),
        ),
        migrations.CreateModel(
            name='ConstructionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est', models.IntegerField()),
                ('pv', models.IntegerField()),
                ('rumbo', models.CharField(blank=True, max_length=255, null=True)),
                ('distancia', models.FloatField()),
                ('v', models.IntegerField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('construccion_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_points', to='sig.constructionframe')),
            ],
        ),
    ]
