# Generated by Django 4.1 on 2024-02-27 06:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0006_remove_constructionframe_distancia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionpoint',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='constructionpoint',
            name='long',
        ),
        migrations.AddField(
            model_name='constructionpoint',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
