# Generated by Django 4.1 on 2024-02-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig', '0007_remove_constructionpoint_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructionpoint',
            old_name='construccion_frame',
            new_name='construction_frame',
        ),
        migrations.AlterField(
            model_name='constructionpoint',
            name='distancia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructionpoint',
            name='est',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructionpoint',
            name='pv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructionpoint',
            name='v',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
