runtime: python39
instance_class: F2

env_variables:
  DJANGO_SETTINGS_MODULE: "terrenos_panoramicos.settings"
  DATABASE_HOST: "/cloudsql/terra-385520:us-central1:terravision-prod"
  DATABASE_USER: "postgres"
  DATABASE_PASSWORD: "2014Mel&MeTVGis"
  DATABASE_NAME: "terravision-prod"
  APPENGINE_URL: https://terra-385520.wn.r.appspot.com