# Generated by Django 4.1 on 2024-01-04 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado de la solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio_Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=50, verbose_name='Servicio a tratar')),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('estado_reunion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reuniones.estado_reunion')),
                ('servicio_reunion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reuniones.servicio_reunion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fechas_Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primera_fecha', models.DateTimeField(verbose_name='Primera fecha')),
                ('segunda_fecha', models.DateTimeField(blank=True, verbose_name='Segunda fecha')),
                ('tercera_fecha', models.DateTimeField(blank=True, verbose_name='Tercera fecha')),
                ('fecha_oficial', models.DateTimeField(null=True, verbose_name='Fecha oficial')),
                ('reunion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reuniones.reunion')),
            ],
        ),
    ]
