# Generated by Django 3.2 on 2021-04-20 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reunion',
            name='fecha_oficial',
        ),
        migrations.AddField(
            model_name='reunion',
            name='estado_reunion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reuniones.estado_reunion'),
        ),
        migrations.AddField(
            model_name='reunion',
            name='servicio_reunion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reuniones.servicio_reunion'),
        ),
        migrations.AlterField(
            model_name='estado_reunion',
            name='estado',
            field=models.CharField(max_length=50, verbose_name='Estado de la solicitud'),
        ),
        migrations.DeleteModel(
            name='Fechas_Reunion',
        ),
    ]
