# Generated by Django 3.2 on 2021-04-20 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0002_auto_20210420_0423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fechas_Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primera_fecha', models.DateTimeField(verbose_name='Primera fecha')),
                ('segunda_fecha', models.DateTimeField(blank=True, verbose_name='Segunda fecha')),
                ('tercera_fecha', models.DateTimeField(blank=True, verbose_name='Tercera fecha')),
                ('fecha_oficial', models.DateTimeField(null=True, verbose_name='Fecha oficial')),
                ('reunion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reuniones.reunion')),
            ],
        ),
    ]
